/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif']
      },
      colors: {
        "inverse-on-surface": "#283239",
        "surface-container": "#172127",
        "surface": "#0a151b",
        "on-background": "#d9e4ed",
        "on-tertiary-container": "#d5ffff",
        "surface-container-low": "#131d23",
        "surface-container-high": "#212b32",
        "on-tertiary-fixed": "#002020",
        "inverse-surface": "#d9e4ed",
        "secondary-fixed": "#ecdcff",
        "secondary-fixed-dim": "#d6baff",
        "on-tertiary": "#003738",
        "outline-variant": "#4e4350",
        "background": "#0a151b",
        "on-error": "#690005",
        "primary": "#edb1ff",
        "outline": "#9a8c9b",
        "on-secondary": "#40147a",
        "on-secondary-fixed": "#270057",
        "on-secondary-container": "#c7a5ff",
        "tertiary-container": "#007e80",
        "on-tertiary-fixed-variant": "#004f51",
        "primary-fixed-dim": "#edb1ff",
        "error-container": "#93000a",
        "on-primary": "#520070",
        "on-primary-container": "#fff3fd",
        "on-surface": "#d9e4ed",
        "on-primary-fixed": "#320046",
        "tertiary-fixed-dim": "#00dce0",
        "surface-tint": "#edb1ff",
        "surface-container-highest": "#2c363d",
        "surface-dim": "#0a151b",
        "primary-fixed": "#f9d8ff",
        "primary-container": "#9d50bb",
        "on-error-container": "#ffdad6",
        "secondary-container": "#573092",
        "inverse-primary": "#883ca6",
        "surface-bright": "#303a42",
        "error": "#ffb4ab",
        "tertiary-fixed": "#0bfbff",
        "on-surface-variant": "#d1c2d2",
        "tertiary": "#00dce0",
        "surface-variant": "#2c363d",
        "surface-container-lowest": "#060f16",
        "on-secondary-fixed-variant": "#573092",
        "secondary": "#d6baff",
        "on-primary-fixed-variant": "#6e208c"
      }
    },
  },
  plugins: [],
}
